dictionary = {"PNC MORTGAGE":"Mortgage",
              "GUSTO":"Income",
              "MEDITECH PAYROLL":"Income",
              "Retail Mobile":"Income",
              "Prime Video":"Amazon",
              "Amazon.com":"Amazon",
              "AMZN Mktp":"Amazon",
              "Market Basket":"Food Shopping",
              "MARKET BASKET":"Food Shopping",
              "Internet Transfer to":"Transfer to Savings",
              "5GUYS":"Eating Out",
              "A L PRIME BEVERLY":"Gas",
              "AMERICAN PETROLEUM":"Gas",
              "Audible":"Amazon",
              "BEVERLY HOSPITAL CABEVERLY MAUS":"Lunches",
              "RITA S CATERING":"Lunches",
              "BAGEL WORLD PEABODY MAUS	":"Eating Out",
              "CHEESECAKE NORTH SHPEABODY MAUS":"Eating Out",
              "DUNKIN":"Eating Out",
              "KIKI":"Eating Out",
              "MCDONALD":"Eating Out",
              "RICHARDSONS ICE CREMIDDLETON MAUS":"Eating Out",
              "STOP & SHOP 0005 PEABODY MAUS":"Food Shopping",
              "TGI FRIDAYS 60658 DEDHAM MAUS":"Eating Out",
              "STP&SHPFUEL":"Gas",
              "AMAZON.COM":"Amazon",
              "TARGET":"Target",
              "SALEM FIVE BANK":"DayCare",
              "ARBELLA MUTUAL ":"Arbella",
              "PAPAGINOS":"Eating Out",
              "BJS WHOLESALE":"Food Shopping",
              "CHASE CREDIT CRD":"Chase Credit Card",
              "NATIONAL GRID NE":"National Grid",
              "AMZNFreeTime":"Amazon",
              "COMCAST":"Comcast",
              "WaterSewer":"Water Bill",
              "BK OF AMER VISA":"Bank of America",
              "BAGEL WORLD PEABODY MAUS":"Eating Out",
              "GreenSky":"Roof Payment",
              "SUNOCO":"Gas",
              "Market Basket":"Food Shopping",
              "T-MOBILE":"T-Mobile",
              "KEYBANK N.A.":"Richie Car Loan",
              "M&M ENERGY LLC":"Gas",
              "Peabody MLP":"Electric Bill",
              "NEW DANVERS HOUSE ODANVERS MAUS":"Eating Out",
              "Amazon.ca":"Amazon",
              "Wal-Mart Store":"Food Shopping",
              "GULF":"Gas",
              "BLUE HILL EXPRE":"Gas",
              "Preauthorized Credit":"Income",
              "SHAWS":"Food Shopping",
              "TACO BELL":"Eating Out",
              "ATM Deposit":"Income",
              "CASHOUT":"Income",
              "PUTNAM PANTRY":"Eating Out",
              "Equity Loan Payment":"Equity Loan",
              "PANERA BREAD":"Eating Out",
              "PETE'S A PLACE":"Eating Out",
              "MA DUA MASS UNEMPLOYMENT DD":"Income",
              "Deposit":"Income",
              "SHOP 0005 PEABODY":"Food Shopping",
              "PEPPYS PIZZA INC SALEM MAUS":"Eating Out",
              "DOMINO":"Eating Out",
              "SIAM DELIGHT":"Eating Out",
              "BEVERLY MOBIL":"Gas",
              "TASTY SUBS BEVERLY MAUS":"Eating Out",
              "BJ'S FUEL":"Gas"
              }
